[package]
name = "broadcaster"
version = "0.0.0"
description = "Lichess Broadcaster"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
askama = "0.12.1"
oauth2 = "4.4.2"
open = "5.0.1"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
serde_urlencoded = "0.7.1"
tauri = { version = "1.5", features = [ "wry", "objc-exception", "updater", "shell-open", "fs-read-dir", "notification-all", "devtools", "fs-read-file", "dialog-open", "reqwest-native-tls-vendored" ], default-features = false }
tauri-plugin-fs-watch = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tiny_http = "0.12.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
