name: CI

on: [push, pull_request]

jobs:
  check-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true
      - run: pnpm tsc

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true
      - run: pnpx prettier --check .

  tests:
    strategy:
      matrix:
        node: [20, latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true
      - run: pnpm test
